[main]
include=~/dotfiles/fuzzel/fuzzel/themes/catppuccin-mocha/blue.ini
font=JetBrains Mono:size=15
icon-theme=Papirus
fields=name,generic,comment,categories,filename
terminal=foot
lines=15
width=40
[colors]
background=1e1e2eff
#background=1e1e2ef2 95+-
