local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.expandtab = true
opt.shiftwidth = 2        -- ваши личные 2 пробела
opt.tabstop = 2
opt.smartindent = true
opt.autoindent = true     -- добавьте эту строку (она нужна для автопар)
opt.wrap = false
opt.swapfile = false
opt.backup = false
opt.hlsearch = false
opt.incsearch = true
opt.termguicolors = true
opt.scrolloff = 4
opt.signcolumn = "yes"
opt.updatetime = 50
opt.colorcolumn = "120"
